services:
  - type: web
    name: reviewpro-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true